import Head from 'next/head'

import styles from '@/styles/Home.module.css'




import ConnectedContainer from '@/components/CakeContainer'
import HookCakeContainer from '@/components/HookCakeContainer'
import HookIceCreamContainer from '@/components/HookIceCreamContainer'


export default function Home() {
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ConnectedContainer />
        <HookCakeContainer />
        <HookIceCreamContainer />

      </main>

    </>
  )
}
